// Auto-generated by deploy.sh / deploy.ps1 - DO NOT EDIT MANUALLY
export const DOWNLOAD_CONFIG = {
  version: '0.0.9',
  releaseNotesUrl: 'https://github.com/vAWK3/mutaba3a/releases/tag/v0.0.9',
  allReleasesUrl: 'https://github.com/vAWK3/mutaba3a/releases',

  mac: {
    fileSize: '~7.16 MB',
    minVersion: 'macOS 12+',
    sha256: '23e4107e7af7669c3d8b1672d531fc1f24ccece018589e01e2bc9c162a69ecde',
    downloadUrl: 'https://github.com/vAWK3/mutaba3a/releases/download/v0.0.9/mutaba3a-v0.0.9-macos-universal.dmg',
  },

  windows: {
    fileSize: '',
    minVersion: 'Windows 10+',
    sha256: '',
    msiUrl: '',
    exeUrl: '',
    exeSha256: '',
  },
};
