// Auto-generated by deploy.sh - DO NOT EDIT MANUALLY
export const DOWNLOAD_CONFIG = {
  version: '0.0.6',
  fileSize: '~5.63 MB',
  minMacos: 'macOS 12+',
  sha256: '0fb17e4ad08ed160f6a10dab51e638f0200e229be9f7c49f0c5bd28419761b52',
  dmgVersionUrl: 'https://github.com/vAWK3/mutaba3a/releases/download/v0.0.6/mutaba3a-v0.0.6-macos-universal.dmg',
  dmgLatestUrl: 'https://github.com/vAWK3/mutaba3a/releases/tag/v0.0.6',
  releaseNotesUrl: 'https://github.com/vAWK3/mutaba3a/releases/tag/v0.0.6',
};
