// Auto-generated by deploy.sh / deploy.ps1 - DO NOT EDIT MANUALLY
export const DOWNLOAD_CONFIG = {
  version: '0.0.7',
  releaseNotesUrl: 'https://github.com/vAWK3/mutaba3a/releases/tag/v0.0.7',
  allReleasesUrl: 'https://github.com/vAWK3/mutaba3a/releases',

  mac: {
    fileSize: '~5.63 MB',
    minVersion: 'macOS 12+',
    sha256: 'f72de6afaf54cbca976526ed53e946448f1041fd3c0de48f85e664b3b22b4fc0',
    downloadUrl: 'https://github.com/vAWK3/mutaba3a/releases/download/v0.0.7/mutaba3a-v0.0.7-macos-universal.dmg',
  },

  windows: {
    fileSize: '',
    minVersion: 'Windows 10+',
    sha256: '',
    msiUrl: '',
    exeUrl: '',
    exeSha256: '',
  },
};
