import type { EngagementLanguage, EngagementType, EngagementCategory } from '../types';

interface EngagementTexts {
  // Document header
  engagementAgreement: string;
  taskEngagement: string;
  retainerEngagement: string;

  // Parties
  provider: string;
  client: string;

  // Sections
  summary: string;
  scope: string;
  deliverables: string;
  exclusions: string;
  dependencies: string;
  timeline: string;
  startDate: string;
  endDate: string;
  milestones: string;
  reviewWindow: string;
  reviews: string;
  revisionRounds: string;
  revisionDefinition: string;
  bugFixPeriod: string;
  payment: string;
  totalAmount: string;
  deposit: string;
  paymentSchedule: string;
  lateFee: string;
  retainerAmount: string;
  billingDay: string;
  rollover: string;
  outOfScopeRate: string;
  relationship: string;
  termType: string;
  terminationNotice: string;
  cancellationCoverage: string;
  ownershipTransfer: string;
  terms: string;
  confidentiality: string;
  ipOwnership: string;
  warranty: string;
  liabilityLimit: string;
  nonSolicitation: string;
  disputeResolution: string;
  governingLaw: string;
  signatures: string;
  legalTerms: string;

  // Values
  days: string;
  rounds: string;
  percent: string;
  enabled: string;
  disabled: string;
  fixed: string;
  monthToMonth: string;
  negotiation: string;
  mediation: string;
  arbitration: string;
  noRollover: string;
  carryForward: string;
  useOrLose: string;
  onSigning: string;
  onMilestone: string;
  onCompletion: string;
  monthly: string;

  // Categories
  design: string;
  development: string;
  consulting: string;
  marketing: string;
  legal: string;
  other: string;

  // Footer
  generatedBy: string;
  page: string;
  of: string;
}

const englishTexts: EngagementTexts = {
  engagementAgreement: 'Engagement Agreement',
  taskEngagement: 'Task-Based Engagement',
  retainerEngagement: 'Retainer Engagement',
  provider: 'Provider',
  client: 'Client',
  summary: 'Summary',
  scope: 'Scope of Work',
  deliverables: 'Deliverables',
  exclusions: 'Exclusions',
  dependencies: 'Dependencies',
  timeline: 'Timeline',
  startDate: 'Start Date',
  endDate: 'End Date',
  milestones: 'Milestones',
  reviewWindow: 'Review Window',
  reviews: 'Reviews & Revisions',
  revisionRounds: 'Revision Rounds',
  revisionDefinition: 'Revision Definition',
  bugFixPeriod: 'Bug Fix Period',
  payment: 'Payment Terms',
  totalAmount: 'Total Amount',
  deposit: 'Deposit',
  paymentSchedule: 'Payment Schedule',
  lateFee: 'Late Payment Fee',
  retainerAmount: 'Monthly Retainer',
  billingDay: 'Billing Day',
  rollover: 'Rollover Rule',
  outOfScopeRate: 'Out-of-Scope Rate',
  relationship: 'Relationship Terms',
  termType: 'Term Type',
  terminationNotice: 'Termination Notice',
  cancellationCoverage: 'Cancellation Coverage',
  ownershipTransfer: 'Ownership Transfer',
  terms: 'Standard Terms',
  confidentiality: 'Confidentiality',
  ipOwnership: 'IP Ownership',
  warranty: 'Warranty Disclaimer',
  liabilityLimit: 'Limitation of Liability',
  nonSolicitation: 'Non-Solicitation',
  disputeResolution: 'Dispute Resolution',
  governingLaw: 'Governing Law',
  signatures: 'Signatures',
  days: 'days',
  rounds: 'rounds',
  percent: '%',
  enabled: 'Enabled',
  disabled: 'Disabled',
  fixed: 'Fixed Term',
  monthToMonth: 'Month-to-Month',
  negotiation: 'Good Faith Negotiation',
  mediation: 'Mediation',
  arbitration: 'Binding Arbitration',
  noRollover: 'No Rollover',
  carryForward: 'Carry Forward',
  useOrLose: 'Use or Lose',
  onSigning: 'On Signing',
  onMilestone: 'On Milestone',
  onCompletion: 'On Completion',
  monthly: 'Monthly',
  design: 'Design',
  development: 'Development',
  consulting: 'Consulting',
  marketing: 'Marketing',
  legal: 'Legal',
  other: 'Other',
  legalTerms: 'Terms and Conditions',
  generatedBy: 'Generated by Mutaba3a',
  page: 'Page',
  of: 'of',
};

const arabicTexts: EngagementTexts = {
  engagementAgreement: 'اتفاقية العمل',
  taskEngagement: 'عمل قائم على المهام',
  retainerEngagement: 'عقد شهري',
  provider: 'مقدم الخدمة',
  client: 'العميل',
  summary: 'الملخص',
  scope: 'نطاق العمل',
  deliverables: 'التسليمات',
  exclusions: 'الاستثناءات',
  dependencies: 'المتطلبات المسبقة',
  timeline: 'الجدول الزمني',
  startDate: 'تاريخ البدء',
  endDate: 'تاريخ الانتهاء',
  milestones: 'المراحل',
  reviewWindow: 'فترة المراجعة',
  reviews: 'المراجعات والتعديلات',
  revisionRounds: 'جولات التعديل',
  revisionDefinition: 'تعريف التعديل',
  bugFixPeriod: 'فترة إصلاح الأخطاء',
  payment: 'شروط الدفع',
  totalAmount: 'المبلغ الإجمالي',
  deposit: 'الدفعة المقدمة',
  paymentSchedule: 'جدول الدفع',
  lateFee: 'رسوم التأخير',
  retainerAmount: 'المبلغ الشهري',
  billingDay: 'يوم الفوترة',
  rollover: 'قاعدة الترحيل',
  outOfScopeRate: 'سعر العمل الإضافي',
  relationship: 'شروط العلاقة',
  termType: 'نوع المدة',
  terminationNotice: 'إشعار الإنهاء',
  cancellationCoverage: 'تغطية الإلغاء',
  ownershipTransfer: 'نقل الملكية',
  terms: 'الشروط القياسية',
  confidentiality: 'السرية',
  ipOwnership: 'ملكية الفكرية',
  warranty: 'إخلاء الضمان',
  liabilityLimit: 'تحديد المسؤولية',
  nonSolicitation: 'عدم الاستقطاب',
  disputeResolution: 'حل النزاعات',
  governingLaw: 'القانون الحاكم',
  signatures: 'التوقيعات',
  days: 'أيام',
  rounds: 'جولات',
  percent: '٪',
  enabled: 'مفعل',
  disabled: 'معطل',
  fixed: 'مدة محددة',
  monthToMonth: 'شهر بشهر',
  negotiation: 'التفاوض بحسن نية',
  mediation: 'الوساطة',
  arbitration: 'التحكيم الملزم',
  noRollover: 'بدون ترحيل',
  carryForward: 'ترحيل للأمام',
  useOrLose: 'استخدم أو افقد',
  onSigning: 'عند التوقيع',
  onMilestone: 'عند المرحلة',
  onCompletion: 'عند الإنجاز',
  monthly: 'شهري',
  design: 'تصميم',
  development: 'تطوير',
  consulting: 'استشارات',
  marketing: 'تسويق',
  legal: 'قانوني',
  other: 'أخرى',
  legalTerms: 'الشروط والأحكام',
  generatedBy: 'تم إنشاؤه بواسطة متابعة',
  page: 'صفحة',
  of: 'من',
};

export function getTexts(language: EngagementLanguage): EngagementTexts {
  return language === 'ar' ? arabicTexts : englishTexts;
}

export function getEngagementTypeLabel(type: EngagementType, language: EngagementLanguage): string {
  const t = getTexts(language);
  return type === 'task' ? t.taskEngagement : t.retainerEngagement;
}

export function getCategoryLabel(category: EngagementCategory, language: EngagementLanguage): string {
  const t = getTexts(language);
  const labels: Record<EngagementCategory, string> = {
    design: t.design,
    development: t.development,
    consulting: t.consulting,
    marketing: t.marketing,
    legal: t.legal,
    other: t.other,
  };
  return labels[category] || t.other;
}
