import type { EngagementLanguage, EngagementType, EngagementCategory } from '../types';

interface EngagementTexts {
  // Document header
  engagementAgreement: string;
  taskEngagement: string;
  retainerEngagement: string;

  // Parties
  provider: string;
  client: string;

  // Sections
  summary: string;
  scope: string;
  deliverables: string;
  exclusions: string;
  dependencies: string;
  timeline: string;
  startDate: string;
  endDate: string;
  milestones: string;
  reviewWindow: string;
  reviews: string;
  revisionRounds: string;
  revisionDefinition: string;
  bugFixPeriod: string;
  payment: string;
  totalAmount: string;
  deposit: string;
  paymentSchedule: string;
  lateFee: string;
  retainerAmount: string;
  billingDay: string;
  rollover: string;
  outOfScopeRate: string;
  relationship: string;
  termType: string;
  terminationNotice: string;
  cancellationCoverage: string;
  ownershipTransfer: string;
  terms: string;
  confidentiality: string;
  ipOwnership: string;
  warranty: string;
  liabilityLimit: string;
  nonSolicitation: string;
  disputeResolution: string;
  governingLaw: string;
  signatures: string;
  legalTerms: string;

  // Values
  days: string;
  rounds: string;
  percent: string;
  enabled: string;
  disabled: string;
  fixed: string;
  monthToMonth: string;
  negotiation: string;
  mediation: string;
  arbitration: string;
  noRollover: string;
  carryForward: string;
  useOrLose: string;
  onSigning: string;
  onMilestone: string;
  onCompletion: string;
  monthly: string;

  // Categories
  design: string;
  development: string;
  consulting: string;
  marketing: string;
  legal: string;
  other: string;

  // Footer
  generatedBy: string;
  page: string;
  of: string;

  // Letter format
  letterSalutation: string;
  letterRe: string;
  letterOpening: string;
  letterOpeningRetainer: string;
  letterClosing: string;
  letterSignOff: string;
  letterSeeSchedules: string;
  byEmail: string;

  // Schedule headers
  scheduleA: string;
  scheduleB: string;
  scheduleC: string;
  scheduleD: string;
  scheduleE: string;

  // Schedule A content
  scopeOfServices: string;
  includedServices: string;

  // Schedule B content
  timelineAndReviews: string;
  projectTimeline: string;
  reviewProcess: string;

  // Schedule C content
  feesAndBilling: string;
  paymentTerms: string;
  paymentTermsTask: string;
  paymentTermsRetainer: string;
  latePaymentClause: string;

  // Schedule D content
  relationshipTerms: string;
  termAndTermination: string;
  ownershipRights: string;
}

const englishTexts: EngagementTexts = {
  engagementAgreement: 'Engagement Agreement',
  taskEngagement: 'Task-Based Engagement',
  retainerEngagement: 'Retainer Engagement',
  provider: 'Provider',
  client: 'Client',
  summary: 'Summary',
  scope: 'Scope of Work',
  deliverables: 'Deliverables',
  exclusions: 'Exclusions',
  dependencies: 'Dependencies',
  timeline: 'Timeline',
  startDate: 'Start Date',
  endDate: 'End Date',
  milestones: 'Milestones',
  reviewWindow: 'Review Window',
  reviews: 'Reviews & Revisions',
  revisionRounds: 'Revision Rounds',
  revisionDefinition: 'Revision Definition',
  bugFixPeriod: 'Bug Fix Period',
  payment: 'Payment Terms',
  totalAmount: 'Total Amount',
  deposit: 'Deposit',
  paymentSchedule: 'Payment Schedule',
  lateFee: 'Late Payment Fee',
  retainerAmount: 'Monthly Retainer',
  billingDay: 'Billing Day',
  rollover: 'Rollover Rule',
  outOfScopeRate: 'Out-of-Scope Rate',
  relationship: 'Relationship Terms',
  termType: 'Term Type',
  terminationNotice: 'Termination Notice',
  cancellationCoverage: 'Cancellation Coverage',
  ownershipTransfer: 'Ownership Transfer',
  terms: 'Standard Terms',
  confidentiality: 'Confidentiality',
  ipOwnership: 'IP Ownership',
  warranty: 'Warranty Disclaimer',
  liabilityLimit: 'Limitation of Liability',
  nonSolicitation: 'Non-Solicitation',
  disputeResolution: 'Dispute Resolution',
  governingLaw: 'Governing Law',
  signatures: 'Signatures',
  days: 'days',
  rounds: 'rounds',
  percent: '%',
  enabled: 'Enabled',
  disabled: 'Disabled',
  fixed: 'Fixed Term',
  monthToMonth: 'Month-to-Month',
  negotiation: 'Good Faith Negotiation',
  mediation: 'Mediation',
  arbitration: 'Binding Arbitration',
  noRollover: 'No Rollover',
  carryForward: 'Carry Forward',
  useOrLose: 'Use or Lose',
  onSigning: 'On Signing',
  onMilestone: 'On Milestone',
  onCompletion: 'On Completion',
  monthly: 'Monthly',
  design: 'Design',
  development: 'Development',
  consulting: 'Consulting',
  marketing: 'Marketing',
  legal: 'Legal',
  other: 'Other',
  legalTerms: 'Terms and Conditions',
  generatedBy: 'Generated by Mutaba3a',
  page: 'Page',
  of: 'of',

  // Letter format
  letterSalutation: 'Dear',
  letterRe: 'Re:',
  letterOpening: 'Thank you for the opportunity to work with you. This engagement letter sets out the terms under which we will provide services to you.',
  letterOpeningRetainer: 'Thank you for the opportunity to work with you on an ongoing basis. This engagement letter sets out the terms of our retainer arrangement.',
  letterClosing: 'We look forward to working with you. Please sign below to indicate your acceptance of these terms.',
  letterSignOff: 'Sincerely,',
  letterSeeSchedules: 'Please see the attached schedules for complete details on scope, timeline, fees, and terms.',
  byEmail: 'By email:',

  // Schedule headers
  scheduleA: 'Schedule A: Scope of Services',
  scheduleB: 'Schedule B: Timeline & Reviews',
  scheduleC: 'Schedule C: Fees & Billing',
  scheduleD: 'Schedule D: Relationship',
  scheduleE: 'Schedule E: Legal Terms',

  // Schedule A content
  scopeOfServices: 'Scope of Services',
  includedServices: 'Included Services',

  // Schedule B content
  timelineAndReviews: 'Timeline & Reviews',
  projectTimeline: 'Project Timeline',
  reviewProcess: 'Review Process',

  // Schedule C content
  feesAndBilling: 'Fees & Billing',
  paymentTerms: 'Payment Terms',
  paymentTermsTask: 'Payment is due according to the schedule above.',
  paymentTermsRetainer: 'Retainer is billed monthly in advance.',
  latePaymentClause: 'Late payments may be subject to a fee.',

  // Schedule D content
  relationshipTerms: 'Relationship Terms',
  termAndTermination: 'Term & Termination',
  ownershipRights: 'Ownership Rights',
};

const arabicTexts: EngagementTexts = {
  engagementAgreement: 'اتفاقية العمل',
  taskEngagement: 'عمل قائم على المهام',
  retainerEngagement: 'عقد شهري',
  provider: 'مقدم الخدمة',
  client: 'العميل',
  summary: 'الملخص',
  scope: 'نطاق العمل',
  deliverables: 'التسليمات',
  exclusions: 'الاستثناءات',
  dependencies: 'المتطلبات المسبقة',
  timeline: 'الجدول الزمني',
  startDate: 'تاريخ البدء',
  endDate: 'تاريخ الانتهاء',
  milestones: 'المراحل',
  reviewWindow: 'فترة المراجعة',
  reviews: 'المراجعات والتعديلات',
  revisionRounds: 'جولات التعديل',
  revisionDefinition: 'تعريف التعديل',
  bugFixPeriod: 'فترة إصلاح الأخطاء',
  payment: 'شروط الدفع',
  totalAmount: 'المبلغ الإجمالي',
  deposit: 'الدفعة المقدمة',
  paymentSchedule: 'جدول الدفع',
  lateFee: 'رسوم التأخير',
  retainerAmount: 'المبلغ الشهري',
  billingDay: 'يوم الفوترة',
  rollover: 'قاعدة الترحيل',
  outOfScopeRate: 'سعر العمل الإضافي',
  relationship: 'شروط العلاقة',
  termType: 'نوع المدة',
  terminationNotice: 'إشعار الإنهاء',
  cancellationCoverage: 'تغطية الإلغاء',
  ownershipTransfer: 'نقل الملكية',
  terms: 'الشروط القياسية',
  confidentiality: 'السرية',
  ipOwnership: 'ملكية الفكرية',
  warranty: 'إخلاء الضمان',
  liabilityLimit: 'تحديد المسؤولية',
  nonSolicitation: 'عدم الاستقطاب',
  disputeResolution: 'حل النزاعات',
  governingLaw: 'القانون الحاكم',
  signatures: 'التوقيعات',
  days: 'أيام',
  rounds: 'جولات',
  percent: '٪',
  enabled: 'مفعل',
  disabled: 'معطل',
  fixed: 'مدة محددة',
  monthToMonth: 'شهر بشهر',
  negotiation: 'التفاوض بحسن نية',
  mediation: 'الوساطة',
  arbitration: 'التحكيم الملزم',
  noRollover: 'بدون ترحيل',
  carryForward: 'ترحيل للأمام',
  useOrLose: 'استخدم أو افقد',
  onSigning: 'عند التوقيع',
  onMilestone: 'عند المرحلة',
  onCompletion: 'عند الإنجاز',
  monthly: 'شهري',
  design: 'تصميم',
  development: 'تطوير',
  consulting: 'استشارات',
  marketing: 'تسويق',
  legal: 'قانوني',
  other: 'أخرى',
  legalTerms: 'الشروط والأحكام',
  generatedBy: 'تم إنشاؤه بواسطة متابعة',
  page: 'صفحة',
  of: 'من',

  // Letter format
  letterSalutation: 'عزيزي',
  letterRe: 'بخصوص:',
  letterOpening: 'نشكركم على فرصة العمل معكم. يحدد خطاب التعاقد هذا الشروط التي سنقدم بموجبها خدماتنا لكم.',
  letterOpeningRetainer: 'نشكركم على فرصة العمل معكم بشكل مستمر. يحدد خطاب التعاقد هذا شروط اتفاقية العقد الشهري بيننا.',
  letterClosing: 'نتطلع للعمل معكم. يرجى التوقيع أدناه للموافقة على هذه الشروط.',
  letterSignOff: 'مع التحية،',
  letterSeeSchedules: 'يرجى الاطلاع على الجداول المرفقة للتفاصيل الكاملة حول النطاق والجدول الزمني والأتعاب والشروط.',
  byEmail: 'بالبريد الإلكتروني:',

  // Schedule headers
  scheduleA: 'الجدول أ: نطاق الخدمات',
  scheduleB: 'الجدول ب: الجدول الزمني والمراجعات',
  scheduleC: 'الجدول ج: الأتعاب والفوترة',
  scheduleD: 'الجدول د: العلاقة',
  scheduleE: 'الجدول هـ: الشروط القانونية',

  // Schedule A content
  scopeOfServices: 'نطاق الخدمات',
  includedServices: 'الخدمات المشمولة',

  // Schedule B content
  timelineAndReviews: 'الجدول الزمني والمراجعات',
  projectTimeline: 'الجدول الزمني للمشروع',
  reviewProcess: 'عملية المراجعة',

  // Schedule C content
  feesAndBilling: 'الأتعاب والفوترة',
  paymentTerms: 'شروط الدفع',
  paymentTermsTask: 'يستحق الدفع وفقاً للجدول أعلاه.',
  paymentTermsRetainer: 'يتم فوترة العقد الشهري مقدماً.',
  latePaymentClause: 'قد تخضع المدفوعات المتأخرة لرسوم إضافية.',

  // Schedule D content
  relationshipTerms: 'شروط العلاقة',
  termAndTermination: 'المدة والإنهاء',
  ownershipRights: 'حقوق الملكية',
};

export function getTexts(language: EngagementLanguage): EngagementTexts {
  return language === 'ar' ? arabicTexts : englishTexts;
}

export function getEngagementTypeLabel(type: EngagementType, language: EngagementLanguage): string {
  const t = getTexts(language);
  return type === 'task' ? t.taskEngagement : t.retainerEngagement;
}

export function getCategoryLabel(category: EngagementCategory, language: EngagementLanguage): string {
  const t = getTexts(language);
  const labels: Record<EngagementCategory, string> = {
    design: t.design,
    development: t.development,
    consulting: t.consulting,
    marketing: t.marketing,
    legal: t.legal,
    other: t.other,
  };
  return labels[category] || t.other;
}
